feat: edit github action to check both binary and trained neural network

diff --git a/.github/workflows/chessboard_analyser.yaml b/.github/workflows/chessboard_analyser.yaml
--- a/.github/workflows/chessboard_analyser.yaml
+++ b/.github/workflows/chessboard_analyser.yaml
@@ -10,7 +10,9 @@ on:
 
 env:
   MIRROR_URL: "git@github.com:EpitechPGE3-2025/G-CNA-500-LYN-5-1-neuralnetwork-4.git"
-  EXECUTABLE: "my_torch_generator"
+  GENERATOR: "my_torch_generator"
+  ANALYSER: "my_torch_analyser"
+  TRAINED_MODEL: "my_torch_network"
 
 jobs:
   check_mirror:
@@ -43,12 +45,44 @@ jobs:
           make fclean
           make all
 
-      - name: Check if EXECUTABLE exist
+      - name: Check if GENERATOR exist
         run: |
-          BINARY=$(echo "${{ env.EXECUTABLE }}" | cut -d' ' -f1)
-          BINARY_PATH=$(find "$(pwd)/" -name "$BINARY" -type f -executable | head -n 1)
+          BINARY=$(echo "${{ env.GENERATOR }}" | cut -d' ' -f1)
+          BINARY_PATH=$(find "$(pwd)/" -name "$BINARY" -type f -GENERATOR | head -n 1)
           if [ -z "$BINARY_PATH" ]; then
             echo "Error during compilation !"
+            exit 1
+          fi
+      - name: Check if ANALYSER exist
+        run: |
+          BINARY=$(echo "${{ env.ANALYSER }}" | cut -d' ' -f1)
+          BINARY_PATH=$(find "$(pwd)/" -name "$BINARY" -type f -ANALYSER | head -n 1)
+          if [ -z "$BINARY_PATH" ]; then
+            echo "Error during compilation !"
+            exit 1
+          fi
+
+  check_trained_model:
+    name: Check trained model
+    needs: check_compilation
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker:latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
+      - name : build project
+        run: |
+          make fclean
+          make all
+
+      - name: Check if TRAINED_MODEL exist
+        run: |
+          MODEL_FILE=$(echo "${{ env.TRAINED_MODEL }}" | cut -d' ' -f1)
+          MODEL_PATH=$(find "$(pwd)/" -name "$MODEL_FILE" -type f -TRAINED_MODEL | head -n 1)
+          if [ -z "$MODEL_PATH" ]; then
+            echo "Trained model file not found !"
             exit 1
           fi
 
